import { ClerkProvider, SignIn } from "@clerk/nextjs";
import type { AppProps } from "next/app";


export const metadata = {
  title: 'Eléctrica Urbano',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{
      variables: {
           fontFamily: 'sans-serif',
       }
   }}>
    <html lang="en">
      <body>{children}</body>
    </html>
    </ClerkProvider>
    
  )
}
